language: scala

scala:
  - 2.12.4
  - 2.11.12

env:
  global:
    - AKKA_TEST_TIMEFACTOR=2.0

sudo: false

script: travis_retry sbt clean coverage test

after_success: sbt coverageReport coveralls

jdk: oraclejdk8